### ISSUE TITLE
Add ability to selectively flatten the JSON output

### ISSUE THREAD

**Issue by bpeterso2000** [json-transformations/jsoncut#1]
Write a companion package called JSON Flatten that integrates with JSON cut.  Similar to https://github.com/amirziai/flatten but with the ability specify which keys to cut (or entire document) using JSON Cut style notation.

**Comment by trp07** [comment]
Going to start working on it Sunday evening.

**Comment by bpeterso2000** [comment]
Thanks 👍

**Comment by bpeterso2000** [comment]
Sample data to play with:

- [Weather Data](https://gist.github.com/bpeterso2000/39f6ab68bd0818c8574f2a4b0012e42c)
- [Earthquake Data](https://gist.github.com/bpeterso2000/b1a0571b333b2c62843ad7e1e25521bc)

**Comment by trp07** [comment]
Thanks

**Comment by trp07** [comment]
Please see PR #6

**Comment by trp07** [comment]
Let me know this implements what you had in mind or I misinterpreted what you wanted.  Also, I'm sure it's far from perfect.  I'm thinking it might need to implement the slice operator, concur?  Anything else for a future iteration?

**Comment by bpeterso2000** [comment]
> Let me know this implements what you had in mind
Yes, this is what I had mind.  I went ahead and accepted the pull request.  

> I'm thinking it might need to implement the slice operator, concur?
Yes.

> Anything else for a future iteration?
Next step would be adding a flatten option to the command-line interface.

**Comment by trp07** [comment]
Ok.  I'll take a look into those.

**Comment by bpeterso2000** [comment]
JSON flatten w/ CLI changes merged.

**Comment by bpeterso2000** [comment]
Temporarily backed flatten out of JSON Cut since `jsonflatten` is being rewritten as a separate package and will be integrated back into JSON Cut after the package is released.  It is also currently undergoing changes to the interface:
* -F, --flat  Flattens entire JSON document.
* -f , --flatten <text> Flattens specified key and any child nodes.

Backed it out so that I can release Issue #2 & Issue #10 while flatten is being rewritten.

**Comment by bpeterso2000** [comment]
JSON Flatten is available here https://github.com/json-transformations/jsonflatten.
