### ISSUE TITLE
Handle embedded dots in key names

### ISSUE THREAD

**Issue by ajkerrigan** [json-transformations/jsoncut#10]
JSON documents with periods embedded in key names seem to trip up jsoncut. The output from `--list` is unclear, and `--get` returns no data for those keys.

[Sample data file](https://gist.github.com/ajkerrigan/081e9ae3cc09683162ea8a23eba632fc)

`--list` output:

```
1 Platform
2 State
3 State.Code
4 State.Name
5 c7n.metrics
6 c7n.metrics.AWS/EC2.CPUUtilization.Average
```

This looks reasonable though misleading. `State.Name` represents nested data while `c7n.metrics` is a single key - in the `--list` output it is hard to tell those cases apart. I'm not sure how important that is, but it's worth noting anyway :).

`--get 4` or `--get State.Name` work as expected, since those keys contain no embedded periods:

```
[
  {
    "Name": "running"
  },
  {
    "Name": "running"
  }
]
```

`--get 5` or `--get c7n.metrics` returns no data:

```
[
  {},
  {}
]
```

Let me know if there is any additional information I can put in this issue that would be helpful. Thanks!

**Comment by bpeterso2000** [comment]
This has been fixed and ready to release.
