### ISSUE TITLE
Add -e, --expand option; expands key numbers to key names

### ISSUE THREAD

**Issue by bpeterso2000** [json-transformations/jsoncut#16]
While key numbers are very nice for interactively transforming data they can change when the data changes.   So for non-interactive use such as scripts the user needs to use key names.  The purpose of the -e, --expand option is to allow the user to interactively transform data and then print the long version of the same command with any key numbers replaced with their respective key names.

**Comment by hugoalvarado** [comment]
So @bpeterso2000, an example of the -e option would be
```
jsoncut -lr2 -e quakes.json
```
which would return
```
jsoncut -lr features quakes.json
```
?
